version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/kurd_word?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: docker
          POSTGRES_DB: kurd_word
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
