# Generated by Django 2.1.1 on 2018-10-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("words", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="word", old_name="creattion_date", new_name="creation_date"
        )
    ]
