# Generated by Django 2.1.1 on 2018-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20181025_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
